# Generated by Django 2.0.2 on 2018-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180411_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrapharticle',
            name='url_page',
        ),
        migrations.AddField(
            model_name='telegrapharticle',
            name='url_page_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='telegrapharticle',
            name='url_page_rus',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='telegrapharticle',
            name='url_page_ua',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='telegrapharticle',
            name='title_article',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
