# Generated by Django 2.0.2 on 2018-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180411_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='telegraph_title',
        ),
        migrations.AddField(
            model_name='post',
            name='url_adres_article',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
